version: '3'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - hadoop_network  

  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9101:9101"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_CREATE_TOPICS: "ticker-HITBTC:1:1,ticker-BEQUANT:1:1"
    networks:
      - hadoop_network  

  kafka-exporter:
    image: bitnami/kafka-exporter:latest
    container_name: kafka-exporter
    depends_on:
      - kafka
    ports:
      - "9308:9308"
    environment:
      JMX_PORT: 9101
      KAFKA_BROKER: kafka:9092
    command: ["--kafka.server=kafka:9092", "--kafka.version=3.6.0"]
    networks:
      - hadoop_network   

  cryptofeed-app:
    image: wuyuefrank/cryptofeed-app:latest
    container_name: cryptofeed-app
    volumes:
      - .:/usr/src/app
    depends_on:
      - kafka
    environment:
      KAFKA_BROKER_URL: "kafka:9092"
    networks:
      - hadoop_network  

networks:
  hadoop_network:
    name: spark_hadoop_network
    external: true
    ipam:
      driver: default
      config:
        - subnet: "172.20.0.0/16"